### ISSUE TITLE
The apps doesnt show up.

### ISSUE THREAD

**Issue by thisismartinn** [nitanmarcel/NothingCore#8]
Xiaomi 13, AOSPA 14, KernelSU with ZygiskNext + LSPosed.

The apps doesnt show up, in settings, or in anywhere. I just recently switched from Magisk to KernelSU, does that affect the module?

**Comment by nitanmarcel** [comment]
I used KernelSU before and it works fine. The module layout should be practically the same and nothing should be different between these too.

Please check if the apps are availayin their system directory, but also in `/data/adb/modules/nothing_core/system`

**Comment by thisismartinn** [comment]
> I used KernelSU before and it works fine. The module layout should be practically the same and nothing should be different between these too.
> 
> Please check if the apps are availayin their system directory, but also in `/data/adb/modules/nothing_core/system`

Just checked... seems like there's nothing at all in there. Is that a problem?

**Comment by nitanmarcel** [comment]
> > I used KernelSU before and it works fine. The module layout should be practically the same and nothing should be different between these too.
> > Please check if the apps are availayin their system directory, but also in `/data/adb/modules/nothing_core/system`
> 
> Just checked... seems like there's nothing at all in there. Is that a problem?

Send me the installation logs for the module

**Comment by thisismartinn** [comment]
[](url)
[KernelSU_install_log_2024-01-12-23-42-46.log](https://github.com/nitanmarcel/NothingCore/files/13921707/KernelSU_install_log_2024-01-12-23-42-46.log)

here you go!

**Comment by nitanmarcel** [comment]
I just tested on android 14, cdroid with kernelsu and all the applications are there for me

**Comment by rshvarya** [comment]
I'm also facing the same issue, previously I tried this on SuperiorOS A14 and then tried it on Project Matrix A14, both times while flashing from Kernelsu, the phone got stuck in the boot loop and when I rebooted the phone (by pressing the power button for some time), it booted but didn't show any app
